#!/usr/bin/env sh

set -eu

[ -f .env ] && . .env

# Install brew
wget -qO - https://git.io/JTlbH?=brew-ubuntu | bash

brew install pre-commit
brew install shfmt
brew install shellcheck
brew install hadolint
brew install bats-core

sudo apt-get update -y || :
sudo apt-get install -y make

# Install libs
[ -d ~/.usr/lib/ ] || mkdir -p ~/.usr/lib/

(
  cd ~/.usr/lib/
  git clone https://github.com/bats-core/bats-support
  git clone https://github.com/bats-core/bats-assert
  git clone https://github.com/bats-core/bats-file

  cat <<-'EOF' >~/.usr/lib/test_helper.bash
  . ~/.usr/lib/bats-support/load.bash
  . ~/.usr/lib/bats-assert/load.bash
  . ~/.usr/lib/bats-file/load.bash

  cd "$BATS_TEST_DIRNAME" || exit
EOF
)
